// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6Pnm98q_-f4u9Io849xw1PtBWsA43P0',
    appId: '1:215144348530:web:e7e42046274925ee26fbeb',
    messagingSenderId: '215144348530',
    projectId: 'matchcode-212ff',
    authDomain: 'matchcode-212ff.firebaseapp.com',
    storageBucket: 'matchcode-212ff.firebasestorage.app',
    measurementId: 'G-PG2TGH24F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjzMbTEnNIsvzzP3NzvHqH52EsALt6Vpc',
    appId: '1:215144348530:android:9410c9cf83923b1d26fbeb',
    messagingSenderId: '215144348530',
    projectId: 'matchcode-212ff',
    storageBucket: 'matchcode-212ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgga66nW8cJ1sBZt1TkLtnog6fw7IZBk',
    appId: '1:215144348530:ios:c6b002cf439a493c26fbeb',
    messagingSenderId: '215144348530',
    projectId: 'matchcode-212ff',
    storageBucket: 'matchcode-212ff.firebasestorage.app',
    iosBundleId: 'com.example.matchcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEgga66nW8cJ1sBZt1TkLtnog6fw7IZBk',
    appId: '1:215144348530:ios:c6b002cf439a493c26fbeb',
    messagingSenderId: '215144348530',
    projectId: 'matchcode-212ff',
    storageBucket: 'matchcode-212ff.firebasestorage.app',
    iosBundleId: 'com.example.matchcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_6Pnm98q_-f4u9Io849xw1PtBWsA43P0',
    appId: '1:215144348530:web:6051e3838d8546c226fbeb',
    messagingSenderId: '215144348530',
    projectId: 'matchcode-212ff',
    authDomain: 'matchcode-212ff.firebaseapp.com',
    storageBucket: 'matchcode-212ff.firebasestorage.app',
    measurementId: 'G-HJVFTPE1ZN',
  );
}
